#!/usr/bin/env bash
# =============================================================================
# build-mac-app.sh — create the Claude Code launcher on macOS.
#
# Deliberately a PLAIN .command file, not a .app bundle. A .command:
#   * needs NO code signing (no Gatekeeper silent-refusal),
#   * runs in a VISIBLE Terminal window (nothing can fail silently),
#   * gets the login-shell PATH (not the .app's stripped LaunchServices PATH),
#   * created locally by the installer, so it carries no quarantine.
# This is the stable, works-every-time launcher. The bundle approach was
# abandoned because macOS fights unsigned script .apps at every turn.
#
# The .command is thin: it resolves the CCDW repo and runs its launch-mac.sh,
# so it always uses the latest launcher after a `git pull`.
#
# Usage:  ./build-mac-app.sh [DEST_DIR]   (DEST_DIR default: "$HOME/Desktop")
# =============================================================================

set -euo pipefail

_SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)"
REPO_DIR="$(cd "${_SELF_DIR}/.." 2>/dev/null && pwd)"

# Known install path baked into the launcher as the first candidate.
INSTALL_REPO_DIR="$HOME/Documents/CCDW"

DEST_DIR="${1:-$HOME/Desktop}"
COMMAND_NAME="Start Claude Code.command"
COMMAND_FILE="${DEST_DIR}/${COMMAND_NAME}"
LAUNCH_SCRIPT_REL="scripts/launch-mac.sh"

log()  { printf '%s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# set_command_icon TARGET — give a plain file the Claude sunburst icon.
# A .command has no bundle, so its custom icon lives in the resource fork:
# sips embeds an icns from the PNG, DeRez extracts it, Rez appends it to the
# target's resource fork, and SetFile flags "has custom icon". Re-applied on
# every build (editing the file drops the fork). Non-fatal if tools are missing.
# ---------------------------------------------------------------------------
set_command_icon() {
    local target="$1"
    local src="${REPO_DIR}/assets/claude-icon.png"
    [ -f "$src" ] || { warn "Icon source not found ($src); skipping icon."; return 0; }
    if ! command -v sips >/dev/null 2>&1 || ! command -v DeRez >/dev/null 2>&1 \
        || ! command -v Rez >/dev/null 2>&1 || ! command -v SetFile >/dev/null 2>&1; then
        warn "Icon tools (sips/Rez/DeRez/SetFile — Xcode CLT) missing; skipping icon."
        return 0
    fi
    local tmp
    tmp="$(mktemp -d)"
    if cp "$src" "$tmp/icon.png" 2>/dev/null \
        && sips -i "$tmp/icon.png" >/dev/null 2>&1 \
        && DeRez -only icns "$tmp/icon.png" > "$tmp/icon.rsrc" 2>/dev/null \
        && Rez -append "$tmp/icon.rsrc" -o "$target" 2>/dev/null; then
        SetFile -a C "$target" 2>/dev/null || true
        log "Applied the Claude sunburst icon."
    else
        warn "Could not apply the custom icon (non-fatal)."
    fi
    rm -rf "$tmp" 2>/dev/null || true
}

[ "$(uname -s)" = "Darwin" ] || die "build-mac-app.sh must run on macOS."
mkdir -p "$DEST_DIR" || die "Cannot create destination dir: $DEST_DIR"

if [ ! -f "${REPO_DIR}/${LAUNCH_SCRIPT_REL}" ]; then
    warn "Expected launcher not found at ${REPO_DIR}/${LAUNCH_SCRIPT_REL}."
    warn "The .command will still be created and will look for the launcher at runtime."
fi

# ---------------------------------------------------------------------------
# Remove stale/abandoned launchers so the Desktop has exactly one obvious icon.
# ---------------------------------------------------------------------------
for stale in \
    "${DEST_DIR}/Claude Code.app" \
    "${DEST_DIR}/Claude Code.webloc" \
    "${DEST_DIR}/Launch Claude Code.command"; do
    if [ -e "$stale" ]; then
        log "Removing old launcher: $stale"
        rm -rf "$stale"
    fi
done

# ---------------------------------------------------------------------------
# Write the .command launcher.
# ---------------------------------------------------------------------------
cat > "$COMMAND_FILE" <<CMD
#!/bin/bash
# Auto-generated by build-mac-app.sh. The Claude Code launcher for macOS.
# Double-click to open a Terminal window and start Claude Code. No signing
# needed; everything is visible so nothing fails silently.

CANDIDATES=(
    "${INSTALL_REPO_DIR}"
    "\$HOME/Documents/CCDW"
    "\$HOME/CCDW"
    "\$HOME/src/CCDW"
)

REPO=""
for c in "\${CANDIDATES[@]}"; do
    if [ -f "\$c/${LAUNCH_SCRIPT_REL}" ]; then
        REPO="\$c"
        break
    fi
done

if [ -z "\$REPO" ]; then
    echo ""
    echo "  Could not find the Claude Code installation (expected ~/Documents/CCDW)."
    echo "  Please run the installer first, then use this launcher."
    echo ""
    read -r -p "  Press Return to close... " _ || true
    exit 1
fi

# Run (not exec) so we can keep the window open if something goes wrong.
"\$REPO/${LAUNCH_SCRIPT_REL}"
rc=\$?
if [ "\$rc" -ne 0 ]; then
    echo ""
    echo "  Something went wrong (code \$rc). Details are in: \$HOME/ccdw-launcher.log"
    read -r -p "  Press Return to close... " _ || true
fi
CMD

chmod +x "$COMMAND_FILE"
xattr -dr com.apple.quarantine "$COMMAND_FILE" 2>/dev/null || true
set_command_icon "$COMMAND_FILE"

# Nudge Finder to pick up the new icon.
touch "$DEST_DIR" 2>/dev/null || true

log ""
log "Created launcher: $COMMAND_FILE"
log "It runs: ${REPO_DIR}/${LAUNCH_SCRIPT_REL} (resolved at runtime)"
