#!/usr/bin/env bash
# =============================================================================
# build-mac-app.sh — (re)build the "Claude Code.app" macOS launcher bundle.
#
# The bundle is deliberately thin: its executable is a tiny bash stub that
# exec's the repo's scripts/launch-mac.sh. Because it references the repo path
# (rather than copying the launcher into the bundle), the .app always runs the
# latest launcher after a git pull — no rebuild required for launcher changes.
#
# Usage:
#   ./build-mac-app.sh [DEST_DIR]
#
#   DEST_DIR   Directory to place "Claude Code.app" in. Default: "$HOME/Desktop".
#
# The build is idempotent: any existing "Claude Code.app" at the destination is
# removed first, then rebuilt from scratch.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Paths.
# ---------------------------------------------------------------------------
# Resolve the repo root from this script's own location (scripts/ -> repo root).
_SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd)"
REPO_DIR="$(cd "${_SELF_DIR}/.." 2>/dev/null && pwd)"

# Known install path baked into the launcher stub. The .app has no repo context
# of its own, so the stub hardcodes this canonical location and falls back to a
# couple of sensible alternatives if it has moved.
INSTALL_REPO_DIR="$HOME/Documents/CCDW"

DEST_DIR="${1:-$HOME/Desktop}"
APP_NAME="Claude Code.app"
APP_DIR="${DEST_DIR}/${APP_NAME}"

ASSETS_DIR="${REPO_DIR}/assets"
ICON_ICNS_SRC="${ASSETS_DIR}/claude-icon.icns"
ICON_PNG_SRC="${ASSETS_DIR}/claude-icon.png"

# The launcher the bundle exec's at runtime.
LAUNCH_SCRIPT_REL="scripts/launch-mac.sh"

log()  { printf '%s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Sanity checks.
# ---------------------------------------------------------------------------
[ "$(uname -s)" = "Darwin" ] || die "build-mac-app.sh must run on macOS."

if [ ! -f "${REPO_DIR}/${LAUNCH_SCRIPT_REL}" ]; then
    warn "Expected launcher not found at ${REPO_DIR}/${LAUNCH_SCRIPT_REL}."
    warn "The bundle will still be built and will look for the launcher at runtime."
fi

mkdir -p "$DEST_DIR" || die "Cannot create destination dir: $DEST_DIR"

# ---------------------------------------------------------------------------
# Idempotent: remove any existing bundle first.
# ---------------------------------------------------------------------------
if [ -e "$APP_DIR" ]; then
    log "Removing existing bundle: $APP_DIR"
    rm -rf "$APP_DIR"
fi

# ---------------------------------------------------------------------------
# Bundle skeleton.
# ---------------------------------------------------------------------------
CONTENTS_DIR="${APP_DIR}/Contents"
MACOS_DIR="${CONTENTS_DIR}/MacOS"
RES_DIR="${CONTENTS_DIR}/Resources"
mkdir -p "$MACOS_DIR" "$RES_DIR"

# ---------------------------------------------------------------------------
# Info.plist.
# ---------------------------------------------------------------------------
# Note: LSBackgroundOnly is intentionally NOT set — we want the app to appear
# and behave normally (Dock icon, focusable) when double-clicked.
cat > "${CONTENTS_DIR}/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Claude Code</string>
    <key>CFBundleDisplayName</key>
    <string>Claude Code</string>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleIdentifier</key>
    <string>com.sleepnumber.ccdw.launcher</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# Launcher stub (Contents/MacOS/launcher).
#
# This is intentionally tiny: it resolves the repo path (hardcoded known
# install location, with fallbacks) and exec's the repo's launch-mac.sh so the
# bundle always runs the latest launcher.
# ---------------------------------------------------------------------------
LAUNCHER_STUB="${MACOS_DIR}/launcher"
cat > "$LAUNCHER_STUB" <<STUB
#!/usr/bin/env bash
# Auto-generated by build-mac-app.sh. Do not edit — rebuild the .app instead.
#
# Resolve the CCDW repo, then exec its launch-mac.sh. The .app carries no repo
# context of its own, so we start from the known install path and fall back to
# a couple of common locations before giving up with a visible error dialog.
set -euo pipefail

# Candidate repo roots, in priority order.
CANDIDATES=(
    "${INSTALL_REPO_DIR}"
    "\$HOME/Documents/CCDW"
    "\$HOME/CCDW"
    "\$HOME/src/CCDW"
)

REPO=""
for c in "\${CANDIDATES[@]}"; do
    if [ -f "\$c/${LAUNCH_SCRIPT_REL}" ]; then
        REPO="\$c"
        break
    fi
done

if [ -z "\$REPO" ]; then
    /usr/bin/osascript -e 'display dialog "Could not find the Claude Code installation (CCDW repo). Expected it at ~/Documents/CCDW. Please reinstall or run the installer, then rebuild this app." buttons {"OK"} default button "OK" with icon caution with title "Claude Code"' >/dev/null 2>&1 || true
    exit 1
fi

exec "\$REPO/${LAUNCH_SCRIPT_REL}"
STUB

chmod +x "$LAUNCHER_STUB"

# ---------------------------------------------------------------------------
# Icon (Contents/Resources/AppIcon.icns).
#
#  1. If assets/claude-icon.icns exists, copy it verbatim.
#  2. Else if assets/claude-icon.png exists, generate an .icns via the standard
#     sips + iconutil iconset pipeline.
#  3. Else warn and skip (the app still runs; it just uses a generic icon).
# ---------------------------------------------------------------------------
ICON_DEST="${RES_DIR}/AppIcon.icns"

generate_icns_from_png() {
    local png="$1" out="$2"
    command -v sips     >/dev/null 2>&1 || { warn "'sips' not found; cannot generate icon."; return 1; }
    command -v iconutil >/dev/null 2>&1 || { warn "'iconutil' not found; cannot generate icon."; return 1; }

    local tmp_root tmp_iconset
    tmp_root="$(mktemp -d)"
    # Clean up the temp dir on ANY return path (success or the || return 1 below)
    # so a mid-way icon failure never orphans a /var/folders temp dir.
    trap 'rm -rf "$tmp_root"' RETURN
    tmp_iconset="${tmp_root}/AppIcon.iconset"
    mkdir -p "$tmp_iconset"

    # Standard iconset sizes (points @ 1x and 2x).
    local sizes=(16 32 128 256 512)
    local s
    for s in "${sizes[@]}"; do
        sips -z "$s"   "$s"   "$png" --out "${tmp_iconset}/icon_${s}x${s}.png"       >/dev/null 2>&1 || return 1
        local s2=$(( s * 2 ))
        sips -z "$s2"  "$s2"  "$png" --out "${tmp_iconset}/icon_${s}x${s}@2x.png"    >/dev/null 2>&1 || return 1
    done

    iconutil -c icns "$tmp_iconset" -o "$out" >/dev/null 2>&1 || return 1
    return 0
}

if [ -f "$ICON_ICNS_SRC" ]; then
    log "Using existing icon: $ICON_ICNS_SRC"
    cp "$ICON_ICNS_SRC" "$ICON_DEST"
elif [ -f "$ICON_PNG_SRC" ]; then
    log "Generating icon from PNG: $ICON_PNG_SRC"
    if ! generate_icns_from_png "$ICON_PNG_SRC" "$ICON_DEST"; then
        warn "Icon generation failed; the app will use a generic icon."
        rm -f "$ICON_DEST"
    fi
else
    warn "No icon found (looked for $ICON_ICNS_SRC and $ICON_PNG_SRC); skipping icon."
fi

# ---------------------------------------------------------------------------
# Strip the quarantine attribute so Gatekeeper doesn't block first launch.
# ---------------------------------------------------------------------------
xattr -dr com.apple.quarantine "$APP_DIR" 2>/dev/null || true

# Nudge Finder/LaunchServices to pick up the new icon promptly.
touch "$APP_DIR" 2>/dev/null || true

log ""
log "Built: $APP_DIR"
log "It launches: ${REPO_DIR}/${LAUNCH_SCRIPT_REL} (resolved at runtime from ~/Documents/CCDW)"
