#!/usr/bin/env bash
# =============================================================================
# Claude Code Docker - Setup Wizard
# Interactive first-run configuration for AI provider credentials
# =============================================================================

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
BOLD='\033[1m'

ENV_FILE="/home/coder/workspace/.env"
SETUP_DONE_MARKER="/home/coder/.claude/.setup-done"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Welcome to Claude Code!${NC}"
echo -e "${BLUE}  Let's get you set up.${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "I need to know how you'll connect to Claude (the AI)."
echo "You have three options:"
echo ""
echo -e "  ${BOLD}1${NC} - Anthropic API Key (personal account at console.anthropic.com)"
echo -e "  ${BOLD}2${NC} - Azure AI Foundry (Claude through your company's Azure account)"
echo -e "  ${BOLD}3${NC} - AWS Bedrock (Claude through your company's AWS account)"
echo ""

while true; do
    read -p "Which option? (1/2/3): " PROVIDER_CHOICE
    case "$PROVIDER_CHOICE" in
        1|2|3) break ;;
        *) echo -e "${YELLOW}Please enter 1, 2, or 3.${NC}" ;;
    esac
done

echo ""

# ---------------------------------------------------------------------------
# Collect credentials based on provider choice
# ---------------------------------------------------------------------------
case "$PROVIDER_CHOICE" in
    1)
        echo -e "${BOLD}Anthropic API Key${NC}"
        echo "You can find this at: https://console.anthropic.com/settings/keys"
        echo ""
        read -sp "Paste your API key (starts with sk-ant-): " API_KEY
        echo ""

        if [[ ! "$API_KEY" =~ ^sk-ant- ]]; then
            echo -e "${YELLOW}That doesn't look like an Anthropic API key (should start with sk-ant-).${NC}"
            read -p "Use it anyway? (y/n): " CONFIRM
            if [ "$CONFIRM" != "y" ]; then
                echo "Setup cancelled. Run this wizard again when you have your key."
                exit 1
            fi
        fi

        cat > "$ENV_FILE" <<EOF
# Claude Code Docker - AI Provider Configuration
# Generated by setup wizard on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Anthropic API Key
ANTHROPIC_API_KEY=$API_KEY

# Ports
TTYD_PORT=7681
CODE_SERVER_PORT=8080
SKILLS_AUTO_UPDATE=1
EOF
        ;;

    2)
        echo -e "${BOLD}Azure AI Foundry${NC}"
        echo "You'll need your Azure endpoint URL and API key from the Azure portal."
        echo ""
        read -p "Azure endpoint URL (e.g., https://your-resource.services.ai.azure.com): " AZURE_URL
        read -sp "Azure API key: " AZURE_KEY
        echo ""

        cat > "$ENV_FILE" <<EOF
# Claude Code Docker - AI Provider Configuration
# Generated by setup wizard on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Azure AI Foundry
ANTHROPIC_BASE_URL=$AZURE_URL
ANTHROPIC_API_KEY=$AZURE_KEY

# Ports
TTYD_PORT=7681
CODE_SERVER_PORT=8080
SKILLS_AUTO_UPDATE=1
EOF
        ;;

    3)
        echo -e "${BOLD}AWS Bedrock${NC}"
        echo "You'll need your AWS credentials with Bedrock access."
        echo ""
        read -p "AWS Access Key ID: " AWS_KEY
        read -sp "AWS Secret Access Key: " AWS_SECRET
        echo ""
        read -p "AWS Region (default: us-east-1): " AWS_REGION
        AWS_REGION=${AWS_REGION:-us-east-1}

        cat > "$ENV_FILE" <<EOF
# Claude Code Docker - AI Provider Configuration
# Generated by setup wizard on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# AWS Bedrock
CLAUDE_CODE_USE_BEDROCK=1
AWS_ACCESS_KEY_ID=$AWS_KEY
AWS_SECRET_ACCESS_KEY=$AWS_SECRET
AWS_REGION=$AWS_REGION

# Ports
TTYD_PORT=7681
CODE_SERVER_PORT=8080
SKILLS_AUTO_UPDATE=1
EOF
        ;;
esac

# ---------------------------------------------------------------------------
# Source the new .env
# ---------------------------------------------------------------------------
set -a
source "$ENV_FILE"
set +a

# Mark setup as done
mkdir -p /home/coder/.claude
touch "$SETUP_DONE_MARKER"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Setup complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "Your credentials are saved in ${BOLD}workspace/.env${NC}"
echo ""
echo -e "Now type ${GREEN}claude${NC} to start Claude Code!"
echo ""
